### ISSUE TITLE
Issue after Successful mint

### ISSUE THREAD

**Issue by md-rifatkhan** [We-Bump/Lighthouse-mint-ui#5]
```
Request failed with status code 404
AxiosError: Request failed with status code 404
    at settle (http://localhost:3000/static/js/bundle.js:299564:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:298246:66)
```

**Comment by md-rifatkhan** [comment]
when shows this error, show successfully minted but not found in wallet.

**Comment by md-rifatkhan** [comment]
my config in mint ui

```
{
    "name":"New",
    "description":"Concept",
    "website":"",
    "twitter":"",
    "discord":"",
    "rpc":"https://rpc.atlantic-2.seinetwork.io",
    "network":"atlantic-2", 
    "collection_address":"address", 
    "nft_name_type": "default",
    "groups": [
        {
          "name": "OG",
          "merkle_root": "41be978fe2bdcdce01143bd422e0e868ad54ed8807a01b8486a20a563399a958"
        },
        {
          "name": "Whitelist",
          "merkle_root": "ea3db28b49c823ad8c32b7b68d3e398c4dcd645cb7a5efb795f1f8a333bfdd1b"
        },
        {
          "name": "Public",
          "merkle_root": null
        }
      ]
}
```

**Comment by sirhercules** [comment]
in order to see it in your wallet you have to manually add the collection to your wallet
